FORBIDDEN_KEYWORDS = [
    "address",
    "where do you live",
    "home address",
    "age",
    "how old are you",
    "birthday",
    "date of birth",
    "family",
    "wife",
    "spouse",
    "kids",
    "children",
    "phone",
    "phone number",
    "email",
    "contact info",
    "ssn",
    "social security",
]